# .github/workflows/deploy.yml
name: Build and Deploy Frontend

on:
  push:
    branches:
      - Release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_WS_URLL: ${{ secrets.VITE_WS_URLL }}
          VITE_CLOUDINARY_CLOUD_NAME: ${{ secrets.VITE_CLOUDINARY_CLOUD_NAME }}
          VITE_CLOUDINARY_API_KEY: ${{ secrets.VITE_CLOUDINARY_API_KEY }}
          VITE_CLOUDINARY_API_SECRET: ${{ secrets.VITE_CLOUDINARY_API_SECRET }}
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}

      - name: Build Project
        run: npm run build

      # Optional: This step now lists the correct 'dist' folder
      - name: List Build Output
        run: ls -l dist

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          # --- FIX 1: Point to the 'dist' folder ---
          source: "dist/*" 
          
          # --- FIX 2: Use 'target' instead of 'remote_path' ---
          target: "/var/www/sona.org.lk/councilor_html"
